# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
