# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-14 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_one', models.CharField(default='', max_length=254)),
                ('address_line_two', models.CharField(default='', max_length=254)),
                ('address_line_three', models.CharField(default='', max_length=254)),
                ('city', models.CharField(default='', max_length=254)),
                ('country', models.CharField(default='', max_length=254)),
                ('postcode', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=254)),
                ('profile_image', models.FileField(upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddon',
            name='userAddon_fk',
        ),
        migrations.DeleteModel(
            name='UserAddon',
        ),
    ]
