# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 15:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200714_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
