# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercreate_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreate',
            old_name='address_line_one',
            new_name='add_Line_Three',
        ),
        migrations.RenameField(
            model_name='usercreate',
            old_name='address_line_three',
            new_name='add_Line_Two',
        ),
        migrations.RenameField(
            model_name='usercreate',
            old_name='profile_image',
            new_name='profile_Image',
        ),
        migrations.RemoveField(
            model_name='usercreate',
            name='address_line_two',
        ),
        migrations.AddField(
            model_name='usercreate',
            name='add_Line_One',
            field=models.CharField(default='', help_text='Apt or Street Number', max_length=254),
        ),
    ]
