# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-30 15:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200730_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='user',
            field=models.OneToOneField(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
