# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200723_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='add_line_one',
            new_name='address_line_one',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='add_line_three',
            new_name='address_line_three',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='add_line_two',
            new_name='address_line_two',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='first_name',
        ),
    ]
