# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20200726_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_one',
            new_name='address_Line_One',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_three',
            new_name='address_Line_Three',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_two',
            new_name='address_Line_Two',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone_Number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='town_or_city',
            new_name='town_or_City',
        ),
    ]
