# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20200726_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='last_Name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
