# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0005_auto_20200729_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='first_Name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_Name',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
